### ISSUE TITLE
Cannot find `java`

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-software/docker-sonar-scanner#45]
When using this image as part of a github action it cannot find `java`

**Comment by JeroenKnoops** [comment]
I'm going to investigate this.

**Comment by JeroenKnoops** [comment]
We've found the issue.

When using this image together with the github `setup-java` the JAVA_HOME path is set differently from the path in the container. This causes the problem.

```
      - name: Set up Java 17
        uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3.9.0
        with:
          java-version: '17'
          distribution: 'microsoft'
```
